version: "3.7"

services:
  redis:
    container_name: redis
    build: ./redis
    env_file: ./.env.dev
    volumes:
      - "./redis/db-data:/data"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-test}
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: exit 0

  db:
    container_name: db
    build: ./db
    env_file: ./.env.dev
    volumes:
      - "./db/db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-test}
      - POSTGRES_DB=${POSTGRES_DB:-test}
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: exit 0

  graphql-api:
    container_name: graphql-api
    hostname: graphql-api
    command: yarn dev
    build:
      context: ./graphql-api
      target: build
    env_file:
      - ".env.dev"
    volumes:
      - "./graphql-api:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
      - DB_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@db:5432/${POSTGRES_DB:-test}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379/0
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "8080:3000"
    networks:
      - backend
      - frontend

  web:
    container_name: web
    hostname: web
    command: yarn dev
    build:
      context: ./web
      target: build
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    environment:
      - API_HOST=localhost:8080
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure
